### ISSUE TITLE
Add support for async exports

### ISSUE THREAD

**Issue by tim-hellhake** [georocket/georocket#120]
Currently the http connection of a search request is kept open until the result is merged and sent to the client.
If the result should be delivered in another format it is necessary to convert it first.
This operation may exceed the http timeout.
Therefore it should be possible to return a preliminary http response to the client.
The response should contain the location of an endpoint where the client can query the current status of the export process.
When the export is finished the client can get the url of the converted result from the status endpoint.

**Comment by michel-kraemer** [comment]
@tim-hellhake Thanks for the issue, but this feature is not necessary. Data conversion should happen outside GeoRocket.
