### ISSUE TITLE
deploy function private

### ISSUE THREAD

**Issue by f7o** [georocket/georocket#149]
https://github.com/georocket/georocket/blob/master/georocket-server/src/main/java/io/georocket/GeoRocket.java#L89

is it neccessary this function is private? shouldn't this be `protected` ?
When i extend georocket i have no change to deploy the http verticle without calling the `start()` function

**Comment by michel-kraemer** [comment]
Yes, you're right. Pull requests are welcome. :-)

**Comment by michel-kraemer** [comment]
Closed by #150
