### ISSUE TITLE
StoreClient Handler Instant End

### ISSUE THREAD

**Issue by f7o** [georocket/georocket#155]
https://github.com/georocket/georocket/blob/master/georocket-client-api/src/main/java/io/georocket/client/StoreClient.java#L405

The handler request will be ended immediately after call. So it's not possible for the caller to determine weather all data is through.

`response.endHandler(res -> ....)` is called right away at start.

**Comment by michel-kraemer** [comment]
Thanks for reporting. Can you please give us a little bit more detail about what you are trying to achieve and what you expect, and what you get instead? Thanks.

**Comment by f7o** [comment]
```java
    storeClient.search(res -> {
        res.result().handler(buf -> log.info(buf.toString());
        res.result().endHandler(buf -> {
            log.info(buf.toString());
            log.info("end of stream reached");
        });
    });
```

The `endHandler()` is called straight away. But it should be called after all or the last http chunk.
I get no trigger weather the end of the readstream is reached.

**Comment by michel-kraemer** [comment]
Are you sure? Because this would be a Vert.x bug.

**Comment by f7o** [comment]
actually i tested it, and the endHandler is never called at all.

**Comment by michel-kraemer** [comment]
Let's have a look at it tomorrow when we meet.

**Comment by michel-kraemer** [comment]
OK. We talked about this issue in person. I'll close it for the time being. Feel free to re-open it if the issue occurs again.
