### ISSUE TITLE
configure index host using system env

### ISSUE THREAD

**Issue by f7o** [georocket/georocket#167]
When starting georocket using docker i have a problem changing the index host:
```
georocket_index_elasticsearch_hosts="['elasticsearch:9200']"
```

The single host config is deprecated and `hosts` is used anyway.
Is there a way to set this array of hosts using environment variables?

**Comment by f7o** [comment]
` georocket_index_elasticsearch_hosts: '["elasticsearch:9200"]'`

for me this works in `docker-compose.yml`, so solved for me!

**Comment by michel-kraemer** [comment]
Just as a follow-up: you can call 

    docker run -e "GEOROCKET_INDEX_ELASTICSEARCH_HOSTS=['elasticsearch:9200']" georocket/georocket
