### ISSUE TITLE
Http Exception while starting Georocket Server

### ISSUE THREAD

**Issue by 82siha1mpg** [georocket/georocket#168]
Hi,
I am using open source version of Georocket. It was running fine earlier, all of a sudden Georocket Server shut down and is not able to start. It gives following exception:
{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}
There is around 60.0 GB memory free on disk, and I am using it on Windows 10. 
How can this issue be resolved?
Thanks a lot in advance.

**Comment by michel-kraemer** [comment]
This seems to be an issue with the embedded Elasticsearch instance. Have you tried installing Elasticsearch separately and disable the `embedded` mode in GeoRocket's config file?

**Comment by michel-kraemer** [comment]
I'm closing this due to no response. If the problem persists, please reopen the ticket. Thanks.
