### ISSUE TITLE
Deprecated parameter in README.md

### ISSUE THREAD

**Issue by bhiemenz** [georocket/georocket#31]
The README.md still recommends the deprecated "georocket.storage.mongodb.host" parameter (chapter "Use a MongoDB container as data store" section 2 "Adjust configuration"). Is this on purpose?

I am not sure as the port is not set at all in the example configuration (so we need no connection string here?), but I think it is confusing to write "georocket.storage.mongodb.host" in the README.md and then link to the default GeoRocket config file, which uses the new parameter "georocket.storage.mongodb.connection_string"

**Comment by michel-kraemer** [comment]
You're probably using an old version. I changed this in 76a32832c6fd75aa8648a790adcd413f614959b9 a couple of days ago.

Or maybe I overlooked something. Please let me know if this is the case. Thanks.

**Comment by michel-kraemer** [comment]
Oh sorry. You meant README.md and not the docs. I'll fix it right away.
