### ISSUE TITLE
Unify way to send failure messages

### ISSUE THREAD

**Issue by bhiemenz** [georocket/georocket#63]
The CLI prints StatusCode and StatusMessage of a server response. Because the error message can be much bigger than StatusMessage supports, the server should send error messages as JSON in the response body. The CLI must print StatusCode, StatusMessage and body then. 

Todo:
- Search code for all response handling (server side) and unify them
- Search code for response printing (client side) and unify them

**Comment by michel-kraemer** [comment]
Superseded by pull request #65
